### ISSUE TITLE
CircularProgressIndicator

### ISSUE THREAD

**Issue by Alijaaan** [slm/progress-state-button#10]
Hi,
I tried to use :
`progressIndicator: CircularProgressIndicator(
    backgroundColor: Colors.white,
    valueColor: AlwaysStoppedAnimation(Colors.red),
    strokeWidth: 1,
  ),`
but it uses default progress indicator with default colors.

**Comment by slm** [comment]
![image](https://user-images.githubusercontent.com/5596316/141099178-48d5192f-3f26-4611-b5f1-84a353c17ec9.png)

I tried with progressIndicator parameter, It seems working. And I'm adding an example on the test.
