### ISSUE TITLE
Unable to change color of button from gray

### ISSUE THREAD

**Issue by fluzzyy** [slm/progress-state-button#2]
If using the example provided where the send state is purple, the button is still always gray even when trying to change it.

**Comment by slm** [comment]
@fluzzyy which example? Custom widget or iconed widget?

**Comment by fluzzyy** [comment]
@slm the one with Icon,  example where it goes from purple to loading to success

**Comment by slm** [comment]
@fluzzyy I made some changes about before. If you can't solve your problem with 1.0.2 please open these issue again.
