### ISSUE TITLE
Change size of button for each ButtonState 

### ISSUE THREAD

**Issue by mikthemonster** [slm/progress-state-button#4]
Hi,

Thanks for this great widget!

I would like to change the appearance of the "success" state to only show an icon and minimize the width of the button (like when loading). Is it possible?

**Comment by trapeye** [comment]
hey u found the answer?

**Comment by mikthemonster** [comment]
No :-(

**Comment by trapeye** [comment]
I'm give up this package after founding this issue tho..

**Comment by slm** [comment]
Hi guys,

I have just added the `minWidthStates` param. You can define the minimum width states. the default value is `loading`, but you can define for multiple states like `minWidthStates: [ButtonState.loading, ButtonState.success]`.
This feature implemented in the 1.0.3 version.

Happy coding. o/
