### ISSUE TITLE
typo: progressIndicatorAligment -> progressIndicatorAlignment

### ISSUE THREAD

**Issue by uPaymeiFixit** [slm/progress-state-button#9]
_progressIndicatorAligment_ should be changed to _progressIndicatorAlig**n**ment_

([typo occurrences](https://github.com/slm/progress-state-button/search?q=progressIndicatorAligment))

Recommend deprecating the property in favor of the correctly spelled one to avoid breaking changes.

It can be annoying at times, but I'd recommend a spell checker like (this one)[https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker].

**Comment by slm** [comment]
thank you @uPaymeiFixit if you have time, can you fix it and create a pr.

**Comment by slm** [comment]
fixed on 1.0.4 thanks
